config/routes.rb
Rails.application.routes.draw do
  root :to => 'application#index'
  devise_for :users
  resources :users do
    resources :foods
  end

  resources :users do
    resources :exercises,  except: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user
  validates_presence_of :name, :calories
  before_save :titleize_name
private
  def titleize_name
    self.name=(name().titleize())
  end
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  validates_presence_of :name, :calories
  before_save :titleize_name
private
  def titleize_name
    self.name=(name().titleize())
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :foods, dependent: :destroy
  has_many :exercises, dependent: :destroy

  def food_calories
    total = 0
    self.foods.each do |food|
      total += food.calories
    end
    return total
  end

  def exercise_calories
    total = 0
    self.exercises.each do |exercise|
      total += exercise.calories
    end
    return total
  end

  def total_calories
    return self.food_calories - self.exercise_calories
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit :username, :email, :password, :password_confirmation
    end
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @exercise = @user.exercises.new
  end

  def create
    @user = User.find(params[:user_id])
    @exercises = @user.exercises.paginate(:page => params[:exercise_paginate], :per_page => 5)
    @foods = @user.foods.paginate(:page => params[:food_paginate], :per_page => 5)
    @exercise = @user.exercises.new(exercise_params)
    if @exercise.save
      flash[:success] = 'Exercise Entry Created'
      respond_to do |format|
        format.html { redirect_to user_path(@user) }
        format.js
      end
    else
      flash[:error] = 'Exercise Unable To Be Saved'
      redirect_to user_path(@user)
    end
  end

  private
    def exercise_params
      params.require(:exercise).permit(:name, :calories)
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @food = @user.foods.new
  end

  def create
    @user = User.find(params[:user_id])
    @foods = @user.foods.paginate(:page => params[:food_paginate], :per_page => 5)
    @exercises = @user.exercises.paginate(:page => params[:exercise_paginate], :per_page => 5)
    @food = @user.foods.new(food_params)
    if @food.save
      flash[:success] = 'Food Entry Created'
      respond_to do |format|
        format.html { redirect_to user_path(@user) }
        format.js
      end
    else
      flash[:error] = 'Food Unable To Be Saved'
      redirect_to user_path(@user)
    end
  end

  private
    def food_params
      params.require(:food).permit(:name, :calories)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    if params[:exercise_sort] && params[:direction] || params[:search]
      @exercises = @user.exercises.order(params[:exercise_sort] + " " + params[:direction]).paginate(:page => params[:exercise_paginate], :per_page => 5)
    else
      @exercises = @user.exercises.paginate(:page => params[:exercise_paginate], :per_page => 5)
    end
    if params[:food_sort] && params[:direction] || params[:search]
      @foods = @user.foods.order(params[:food_sort] + " " + params[:direction]).paginate(:page => params[:food_paginate], :per_page => 5)
    else
      @foods = @user.foods.paginate(:page => params[:food_paginate], :per_page => 5)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end

  def sortable(column, title = nil, type, user)
    eval 'title ||= column.titleize
    direction = column == params[:' + type + '_sort] && params[:direction] == "asc" ? "desc" : "asc"
    link_to title, user_path(user, :' + type + '_sort => column, :direction => direction)'
  end
end

app/views/application/index.html.erb
<%= render 'layouts/flash' %>

<h1 class="title-font">Cannon Beach Body</h1>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag 'cannon-beach-body.jpg' %>
    </div>

    <div class="item">
      <%= image_tag 'cannon-beach-biker.jpg' %>
    </div>

    <div class="item">
      <%= image_tag 'cannon-beach-yoga.jpg' %>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div id="user-index">
  <div class="row">
    <div class="col-xs-4">
      <h3>Get the svelte and taut Cannon Beach Body you've always dreamed of</h3>
    </div>
    <div class="col-xs-4">
      <h3>Track your calories from food and set intake limits</h3>
    </div>
    <div class="col-xs-4">
      <h3>Track calories burned through exercise and set fitness goals</h3>
    </div>
  </div>

<% if current_user %>
    <h3>Welcome, <%= current_user.email %></h3>
    <h3><%= link_to "Go to your Dashboard", user_path(current_user), class:"btn btn-primary" %></h3>
  </div>
<% else %>
  <div class="row">
    <div class="col-xs-6">
      <h3>Want to get Started?</h3>
      <h3><%= link_to "SIGN UP NOW!", new_user_registration_path %></h3>
    </div>
    <div class="col-xs-6">
      <h3>Already a member?</h3>
      <h3><%= link_to "Sign in here!", new_user_session_path %></h3>
    </div>
  </div>
<% end %>

app/views/exercises/_form.html.erb
<%= form_for [@user, @exercise], remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :calories %>
  <%= f.text_field :calories %>
  <%= f.submit %>
<% end %>

app/views/exercises/_show.html.erb
<% if @user.exercises.any? %>
  <%= sortable "name", "Sort By Name", "exercise", @user %>
  <%= sortable "calories", "Sort By Calories", "exercise", @user %>
  <% @exercises.each do |exercise| %>
    <p><%= exercise.name %>: <%= exercise.calories %></p>
  <% end %>
  <%= will_paginate @exercises, :params => { :controller => 'users', :action => 'show', :id => @user.id }, :param_name => 'exercise_paginate' %>
  <h4>Total: <%= @user.exercise_calories %> calories burned</h4>
  <hr>
<% end %>

app/views/exercises/create.js.erb
$('form').remove();
$('#new_user_exercise_link').show();
$('#exercise_show').html('<%= j render "show" %>');
$('#chart_row').html('<%= j render "users/charts" %>')
$('#total_calories').html('<%= j render "users/total" %>')
$('#flash').html('<%= j render "layouts/flash" %>')

app/views/exercises/new.html.erb
<%= render 'form' %>

app/views/exercises/new.js.erb
$('#new_user_exercise_link').hide().after('<%= j render("form") %>')

app/views/foods/_form.html.erb
<%= form_for [@user, @food], remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :calories %>
  <%= f.text_field :calories %>
  <%= f.submit %>
<% end %>

app/views/foods/_show.html.erb
<% if @user.foods.any? %>
  <%= sortable "name", "Sort By Name", "food", @user %>
  <%= sortable "calories", "Sort By Calories", "food", @user %>
  <% @foods.each do |food| %>
    <p><%= food.name %>: <%= food.calories %></p>
  <% end %>
  <%= will_paginate @foods, :params => { :controller => 'users', :action => 'show', :id => @user.id }, :param_name => 'food_paginate' %>
  <h4>Total: <%= @user.food_calories %> calories consumed</h4>
  <hr>
<% end %>

app/views/foods/create.js.erb
$('form').remove();
$('#new_user_food_link').show();
$('#food_show').html('<%= j render "show" %>');
$('#chart_row').html('<%= j render "users/charts" %>')
$('#total_calories').html('<%= j render "users/total" %>')
$('#flash').html('<%= j render "layouts/flash" %>')

app/views/foods/new.js.erb
$('#new_user_food_link').hide().after('<%= j render("form") %>')

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cannon Beach Body</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Faster+One" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar" role="navigation">
      <div class ='container'>
        <div class="navbar-header">
          <%= link_to "CBB", root_path, id:"homelink" %>
        </div>
        <div class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            Logged in as <%= current_user.email %> |
            <%= link_to "View Profile", user_path(current_user.id) %> |
            <%= link_to "Edit Profile", edit_user_registration_path %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %> |
            <%= link_to "Sign Up", new_user_registration_path, :method => "get" %></button>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_charts.html.erb
<div id="food-charts" class="col-xs-6">
  <%= pie_chart @user.foods.group(:name).count %>
  <%= bar_chart @user.foods.group(:name).sum(:calories) %>
</div>

<div id="exercise-charts" class="col-xs-6">
  <%= pie_chart @user.exercises.group(:name).count %>
  <%= bar_chart @user.exercises.group(:name).sum(:calories) %>
</div>

app/views/users/_total.html.erb
<h3>Cumulative Total: <%= @user.total_calories %> calories!</h3>
<% if @user.total_calories < 0 %>
  <h4>Nice job <%= @user.email %>!</h4>
<% else %>
  <h4>You need to go exercise, fatso!</h4>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div id="flash">
  <%= render 'layouts/flash' %>
</div>

<h1 class="title-font">Dashboard</h1>

<div id="total_calories">
  <%= render "total" %>
</div>

<div class="row">
  <div class="col-xs-6">
    <%= link_to 'Add Food', new_user_food_path(@user), id: 'new_user_food_link', remote: true, method: 'get', class: 'btn-lg btn btn-success' %>
    <hr>
    <div id="food_show">
      <%= render "foods/show" %>
    </div>
  </div>

  <div class="col-xs-6">
    <%= link_to 'Add Exercise', new_user_exercise_path(@user), id: 'new_user_exercise_link', remote: true, method: 'get', class: 'btn-lg btn btn-success' %>
    <hr>
    <div id="exercise_show">
      <%= render "exercises/show" %>
    </div>
  </div>
</div>
<div id="chart_row" class="row">
  <%= render "charts" %>
</div>